name: Simple shell commands 

on: [push]

jobs:
    Shell-commands:
        runs-on: ubuntu-20.04
        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: commands
              run: |
                echo "Welcome to GitHub Actions"
                pwd
                Shell-commands:
                    runs-on: ubuntu-20.04
                    steps:
                        - name: checkout
    python:
        runs-on: ubuntu-20.04
        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: setup python 3.10 
              uses: actions/setup-python@v4
              with:
                python-version: 3
            
            - name: Run Python script
              run: python3 Hello-Python.py
              
               
    run-windows-commands:
        runs-on: windows-latest
        steps:
            - name: Directory
              run: Get-Location
            - name: Directory bash
              run: pwd
              shell: bash