name: Simple shell commands 

on: [push]

jobs:
    Shell-commands:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - name: checkout
              run: |
                echo "Welcome to GitHub Actions"
                pwd
